import type { Metadata } from "next";
import { Bricolage_Grotesque } from "next/font/google";
import ThemeProvider from "../providers/ThemeProvider";

const bricolage_grotesque = Bricolage_Grotesque({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ThemeProvider>
      <html lang="en">
        <body
          className={bricolage_grotesque.className}
          suppressHydrationWarning
        >
          {children}
        </body>
      </html>
    </ThemeProvider>
  );
}
